# Site Settings
title:               AI Marine
tagline:             a minimalist Jekyll theme
description:
baseurl:            #"/Lagrange"
url:                #"https://leimao.github.io/"
github:
  url:               #"https://leimao.github.io/"
author:
  name:              "Lei Mao"
  email:             "dukeleimao@gmail.com"
  twitter:           
  instagram:         
  github:            "leimao"
  facebook:          
  linkedin:          "leimao"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
