# Site Settings
title:               "Red Queen"
tagline:             "A Blog from an Artificial Intelligence Maverick"
description:
baseurl:            
url:                 #"https://leimao.github.io/"
github:
  url:               #"https://leimao.github.io/"
author:
  name:              "Lei Mao"
  email:             "dukeleimao@gmail.com"
  twitter:           
  instagram:         
  github:            "leimao"
  facebook:          
  linkedin:          "lei-mao"
navigation:
- title: Blog
  url: /blog
- title: About
  url: /about
- title: Contact
  url: /contact

paginate:            5
disqus:              "leimao-github-io"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
